# Generated by Django 4.1.5 on 2023-01-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='document',
            field=models.BigIntegerField(),
        ),
    ]
